### ISSUE TITLE
Not actually FOSS

### ISSUE THREAD

**Issue by darkf** [asteriskman7/dldtg#7]
Copyright is held exlusively by the author and no license is given to redistribute or modify it, so this is *mostly* useless.

**Comment by asteriskman7** [comment]
I was unclear on my aspirations for this project for a long time so I kept the original copyright to give myself the most flexibility. At this point, I think that most of those aspirations are gone. I'll try to pick a different license some time in the next few days.

**Comment by darkf** [comment]
Thanks, sounds like a plan! A lot of the stuff from the TODO list in the info tab is easily improved on.

**Comment by asteriskman7** [comment]
This is taking longer than I had hoped. I did decide on GPLv3. Just need to add appropriate license text to all files.

**Comment by asteriskman7** [comment]
I've added the GPLv3 LICENSE.txt file and modified the header of source files to reference that license. This issue is now resolved.
